# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 681f2808302de7143bbae1d80342c4f6a7821001c0bb005d5583ee17f124e37620e44fa42c62e990313b328ca3128cdeffa2caf290323b6474bc53ba2e71754d

test:
  secret_key_base: 4a2413926d3ebcff818df62a20130af4ced19881d8ff0c0f9a7f3433252dc01d297c6a21e6508dba02344fb19d7f4eedf79845f457b2e9625897dc8cd8294888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
